# Generated by Django 5.1.1 on 2024-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdata_codechef_alter_userdata_codeforces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='none', max_length=11),
        ),
    ]
